apiVersion: v2
name: kueue-visualizer-chart
description: Kueue visibility plugin for the RHOAI Dashboard
type: application
version: 0.1.1
appVersion: "0.1.1"
keywords:
  - rhoai
  - openshift-ai
  - plugin
  - kueue
home: https://github.com/rh-ai-community-plugins/kueue-visualizer
sources:
  - https://github.com/rh-ai-community-plugins/kueue-visualizer
