image:
  repository: quay.io/rh-ai-community-plugins/kueue-plugin
  tag: ""
  pullPolicy: IfNotPresent

# Overrides .Chart.Name — set if release name differs from chart name
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

route:
  enabled: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

securityContext:
  runAsNonRoot: true

