apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kueue-plugin.fullname" . }}
  labels:
    app: {{ include "kueue-plugin.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kueue-plugin.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kueue-plugin.fullname" . }}
    spec:
      serviceAccountName: {{ include "kueue-plugin.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: kueue-plugin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
