apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kueue-visualizer.fullname" . }}
  labels:
    {{- include "kueue-visualizer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kueue-visualizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kueue-visualizer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kueue-visualizer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ include "kueue-visualizer.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
