{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kueue-visualizer.serviceAccountName" . }}
  namespace: {{ include "kueue-visualizer.namespace" . }}
  labels:
    {{- include "kueue-visualizer.labels" . | nindent 4 }}
{{- end }}
